name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli zip

    - name: Zip application
      run: zip -r app.zip . -x "*.git*"

    - name: Upload ZIP to S3
      run: |
        aws s3 cp app.zip s3://elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}/app-${GITHUB_RUN_ID}.zip

    - name: Create new Elastic Beanstalk version
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name "studentperformance" \
          --version-label "v-${GITHUB_RUN_ID}" \
          --source-bundle S3Bucket="elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="app-${GITHUB_RUN_ID}.zip"

    - name: Deploy to Elastic Beanstalk environment
      run: |
        aws elasticbeanstalk update-environment \
          --environment-name "Studentperformance-env" \
          --version-label "v-${GITHUB_RUN_ID}"
